DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS proyectos CASCADE;
DROP TABLE IF EXISTS notas_g CASCADE;
DROP TABLE IF EXISTS notas CASCADE;
DROP TABLE IF EXISTS tareas CASCADE;
DROP TABLE IF EXISTS alertas CASCADE;
DROP TABLE IF EXISTS es_miembro CASCADE;
DROP TABLE IF EXISTS subtareas CASCADE;


DROP TABLE IF EXISTS accesos CASCADE;
