DROP TABLE IF EXISTS es_miembro CASCADE;
DROP TABLE IF EXISTS salas CASCADE;
DROP TABLE IF EXISTS ha_jugado CASCADE;
DROP TABLE IF EXISTS partidas_acabadas CASCADE;
DROP TABLE IF EXISTS amigo_de CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;